# -*- coding: utf-8 -*-
"""Kvintána — vendor the webfonts locally.

Downloads the woff2 files Google Fonts would serve and writes assets/fonts/
plus assets/css/fonts.css.

Why not just link fonts.googleapis.com:
  · two render-blocking requests to a third party on every page load
  · every visitor's IP reaches Google — a live GDPR question in the EU
  · a self-hosted file can be <link rel=preload>ed; a stylesheet import cannot

Run once; the output is committed. Re-run only to change weights or axes.

    python3 tools/build_fonts.py
"""

import os
import re
import sys
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "assets", "fonts")
CSS = os.path.join(ROOT, "assets", "css", "fonts.css")

# A modern browser UA, or Google serves the legacy truetype build.
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")

FAMILIES = [
    # (label, Google css2 query, local basename)
    ("Fraunces",
     "family=Fraunces:ital,opsz,wght,SOFT,WONK@0,9..144,300..700,0..100,0..1;"
     "1,9..144,300..700,0..100,0..1",
     "fraunces"),
    ("Instrument Sans",
     "family=Instrument+Sans:ital,wght@0,400..700;1,400..600",
     "instrument-sans"),
]

# Czech needs latin-ext (ě š č ř ž ů ď ť ň). Keep both, drop everything else.
KEEP = ("latin", "latin-ext")


def fetch(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read() if binary else r.read().decode("utf-8")


def main():
    os.makedirs(OUT, exist_ok=True)
    blocks = []

    for label, query, base in FAMILIES:
        css = fetch("https://fonts.googleapis.com/css2?%s&display=swap" % query)

        # Google emits a "/* latin-ext */" comment before each @font-face.
        chunks = re.split(r"/\*\s*([\w-]+)\s*\*/", css)
        pairs = list(zip(chunks[1::2], chunks[2::2]))
        kept = 0

        for subset, block in pairs:
            if subset not in KEEP:
                continue
            m = re.search(r"src:\s*url\((https://[^)]+\.woff2)\)", block)
            if not m:
                continue
            style = "italic" if "font-style: italic" in block else "normal"
            name = "%s-%s-%s.woff2" % (base, subset, style)
            path = os.path.join(OUT, name)
            if not os.path.exists(path):
                with open(path, "wb") as f:
                    f.write(fetch(m.group(1), binary=True))
            blocks.append(
                block.replace(m.group(1), "/assets/fonts/" + name).strip())
            kept += 1
            print("  %-16s %-10s %-8s %s" % (label, subset, style, name))

        if not kept:
            sys.exit("No woff2 found for %s — Google's CSS format changed." % label)

    header = (
        "/* Generated by tools/build_fonts.py — do not edit by hand.\n"
        "   Self-hosted so no visitor request reaches Google. */\n\n")
    with open(CSS, "w", encoding="utf-8") as f:
        f.write(header + "\n\n".join(blocks) + "\n")

    total = sum(os.path.getsize(os.path.join(OUT, f)) for f in os.listdir(OUT))
    print("Wrote %s (%d files, %.0f KB)" % (CSS, len(os.listdir(OUT)), total / 1024))


if __name__ == "__main__":
    main()
